config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :topic
	has_many :comments, dependent: :destroy
	
	validates_presence_of :title, :body, :topic
	validates_associated :topic

	def self.featured_blogs
		limit(2)
	end

	def self.recent_blogs
		order(created_at: "DESC")
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:toggle_status, :destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent_blogs.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent_blogs.page(params[:page]).per(5)
    end
    @page_name = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_name = @blog.title
      #@seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page."
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @topics = Topic.all
  end

  # GET /blogs/1/edit
  def edit
    @topics = Topic.all
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Post was successfully created.' }
        #format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Post was successfully updated.' }
        #format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: 'Post status was successfully udpated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_sidebar_topics
      @side_bar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def gravatar_helper(user)
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 40
	end

	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

		options = {
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_blocks: true
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end

	def status_admin_action(blog_obj)
		if blog_obj.published?
			link_to fa_icon('toggle-on'), toggle_status_blog_path(blog_obj), title: "Switch to Draft", class: "nav-link status-toggle"
		else
			link_to fa_icon('toggle-off'), toggle_status_blog_path(blog_obj), title: "Switch to Published", class: "nav-link status-toggle"
		end
	end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <!-- Start of admin-nav -->
  <ul class="nav admin-nav breadcrumb justify-content-start">
  	<li class="nav-item">
  		<%= status_admin_action(blog) if logged_in?(:site_admin) %>
  	</li>
  	<li class="nav-item">
  		<%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog), class: "nav-link", title: "Edit Post" if logged_in?(:site_admin) %>
  	</li>
  	<li class="nav-item">
  		<%= link_to fa_icon('trash-o'), blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "nav-link", title: "Delete Post" if logged_in?(:site_admin) %>
  	</li>
  </ul>
  <!--/ End of admin-nav -->
<% end %>

app/views/blogs/_blog.html.erb
<!-- Start of blog-post -->
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">
    <%= blog.status === "published" ? "Published " : "Drafted " %>
    <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago
  </p>
  
  <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>

  <p>
    <%= blog.body %>
  </p>
</div>
<!-- / End of blog-post -->

app/views/blogs/_form.html.erb
<!-- Start of blog form -->
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator(error, "Error") %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Enter a Title..." %>
  </div>

  <div class="form-group">
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, @topics, :id, :title, 
                              {
                                selected: blog.topic_id,
                                include_blank: true
                              },
                              class: "form-control custom-select"
                            ) 
    %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: "form-control", rows: "15", placeholder: "Enter Content..." %>
  </div>

  <div class="form-group">
    <label class="custom-control custom-radio">
      <%= f.radio_button(:status, "draft",
                          {
                            class: "custom-control-input"
                          }
                        )
      %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Draft</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button(:status, "published",
                          {
                            class: "custom-control-input"
                          }
                        )
      %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Published</span>
    </label>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
<!--/ End of blog form -->

app/views/blogs/edit.html.erb
<!-- Start of blog-main -->
<div class="col-sm-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>
<!--/ End of blog-main -->

app/views/blogs/index.html.erb
<!-- Start of blog-main -->
<div class="col-sm-8 blog-main">

  <%= paginate @blogs %>

  <%= render @blogs %>

  <%= paginate @blogs %>

</div>
<!--/ End of blog-main -->

app/views/blogs/new.html.erb
<!-- Start of blog-main -->
<div class="col-sm-8 blog-main">

  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>

</div>
<!--/ End of blog-main -->

app/views/blogs/show.html.erb
<!-- Start of blog-main -->
<div class="col-sm-8 blog-main">
  <!-- Start of breadcrumb -->
  <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: "breadcrumb-item" %>
    <span class="breadcrumb-item active"><%= @blog.title %></span>

    <%  if logged_in?(:site_admin) %>
    <!-- Start of dropdown -->
    <div class="dropdown pull-right show">
      <a class="btn btn-default" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Actions">
        <%= fa_icon('ellipsis-v') %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to fa_icon('pencil-square-o') + " Edit", edit_blog_path(@blog), class: "dropdown-item text-center" if logged_in?(:site_admin) %>
        <%= link_to fa_icon('trash-o') + " Delete", @blog, data: { confirm: 'Are you sure you want to delete this post?' }, class: "dropdown-item text-center" if logged_in?(:site_admin) %>
      </div>
    </div>
    <!--/ End of dropdown -->
    <% end %>
  </nav>
  <!--/ End of breadcrumb -->

  <h2><%= @blog.title %></h2>
  <p>
    <%= markdown @blog.body %>
  </p>

  <!-- Start of comment form -->
  <%= render 'comments/comment_form' %>
  <!--/ End of comment form -->

  <!-- Start of comments -->
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
  <!--/ End of comments -->

</div>
<!--/ End of blog-main -->