config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies,
																allow_destroy: true,
																reject_if: lambda { |attrs| attrs['name'].blank? }
	validates_presence_of :title, :body

	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	def self.angular
		where(subtitle: "Angular")
	end

	def self.ruby_on_rails
		where(subtitle: "Ruby on Rails")
	end

	def self.by_position
		order("position ASC")
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
	layout "portfolio"
	access all: [:show, :index], user: {except: [:sort, :destroy, :new, :create, :update, :edit]}, site_admin: :all

	def index
		@portfolio_items = Portfolio.by_position
	end

	def sort
		params[:order].each do |key, value|
			Portfolio.find(value[:id]).update!(position: value[:position])
		end

		render nothing: true
	end

	def new
		@portfolio_item = Portfolio.new
	end

	def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item was successfully created.' }
        #format.json { render :show, status: :created, location: @portfolio_items }
      else
        format.html { render :new }
        #format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    #redirect to index page
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
        #format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    #destroy the record
    @portfolio_item.destroy

    #redirect to index page
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio item has been deleted'}
      #format.json {head :no_content}
    end
  end

  private
		# Use callbacks to share common setup or constraints between actions.
		def set_portfolio_item
			#perform lookup
	    @portfolio_item = Portfolio.find(params[:id])
		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
																				:main_image,
																				:thumb_image,
                                        technologies_attributes: [:id, :name, :_destroy]
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end

	def portfolio_img(img, type)
		if img.model.main_image? || img.model.thumb_image?
			img
		elsif type == "thumb"
			image_generator(height: '350', width: '200')
		elsif type == "main"
			image_generator(height: '600', width: '400')
		end
	end
end

app/views/portfolios/_form.html.erb
<!-- Start of portfolio-form -->
<%= form_for(portfolio_item) do |f| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error, "Error") %>
    <% end %>
  <% end %>

  <div class="row">

    <div class="col-md-6">

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.file_field :main_image, style: "display:none", class: "file" %>
        <div class="input-group col-xs-12">
          <span class="input-group-addon">
            <%= fa_icon('picture-o') %>
          </span>
          <input type="text" class="form-control input-lg" disabled placeholder="Upload a main image file">
          <span class="input-group-btn">
            <button class="browse btn btn-primary input-lg" type="button">
              <%= fa_icon('search') %>
              Browse
            </button>
          </span>
        </div>
      </div>

      <div class="form-group">
        <%= f.file_field :thumb_image, style: "display:none", class: "file" %>
        <div class="input-group col-xs-12">
          <span class="input-group-addon">
            <%= fa_icon('picture-o') %>
          </span>
          <input type="text" class="form-control input-lg" disabled placeholder="Upload a thumb image file">
          <span class="input-group-btn">
            <button class="browse btn btn-primary input-lg" type="button">
              <%= fa_icon('search') %>
              Browse
            </button>
          </span>
        </div>
      </div>

    </div>

    <div class="col-md-6">

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: "10" %>
      </div>

    </div>

    <hr>

    <div class="col-md-12">

      <h3>Technologies Used</h3>      
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render "technology_fields", f: technology_form %>
        <% end %>
      </div>

      <div>
        <%= link_to_add_association fa_icon('plus-circle') + ' Add Technology', f, :technologies, class: "btn btn-primary mb-4" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save Portfolio", class: "btn btn-primary btn-block" %>
      </div>

    </div>

  </div>
<% end %>
<!--/ End of portfolio-form -->

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
	<!-- Start of portfolio-item -->
	<div class="card w-100" data-portfolio-id="<%= portfolio_item.id %>">
	  <%= image_tag portfolio_img(portfolio_item.thumb_image, "thumb"), width: '100%' %>
	  <p class="card-text">
	    <span><%= link_to portfolio_item.title, show_portfolio_path(portfolio_item) %></span>
	    <%= portfolio_item.subtitle %>
	  </p>
	</div>
	<!--/ End of portfolio-item -->
</div>

app/views/portfolios/_technology_fields.html.erb
<!-- Start of nested-fields -->
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control mb-1" %>
  <%= link_to_remove_association "Remove Technology", f %>
</div>
<!--/ End of nested-fields -->

app/views/portfolios/edit.html.erb
<!-- Start of container -->
<div class="container mt-4">

  <h1>Edit this portfolio item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>

</div>
<!--/ End of container -->

app/views/portfolios/index.html.erb
<!-- Start of album -->
<div class="album text-muted">

  <!-- Start of container -->
  <div class="container">

  	<%= source_helper("alert alert-info") %>

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">

      <%= render partial: 'portfolio_item', collection: @portfolio_items %>

    </div>

  </div>
  <!--/ End of container -->

</div>
<!--/ End of album -->

app/views/portfolios/new.html.erb
<!-- Start of container -->
<div class="container mt-4">

  <h1>Create a new portfolio item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>

</div>
<!--/ End of container -->

app/views/portfolios/show.html.erb
<!-- Start of container -->
<div class="container mt-4">

	<div class="row">

		<div class="col-md-7">
			<%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: "100%" %>
		</div>

		<div class="col-md-5">
			<h2><%= @portfolio_item.title %></h2>

			<em><%= @portfolio_item.subtitle %></em>

			<p><%= @portfolio_item.body %></p>

			<% if !@portfolio_item.technologies.empty? %>
				<h3>Technologies used</h3>
				<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %></p>
				<% end %>
			<% end %>

			<% if logged_in?(:site_admin) %>
				<%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: "btn btn-warning" %>
			<% end %>
		</div>

	</div>

</div>
<!--/ End of container -->