config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], :title => "Alert") %>
<% elsif flash[:error] %>
	<%= js add_gritter(flash[:error], :title => "Error") %>
<% else %>
	<%= js add_gritter(flash[:notice], :title => "") %>
<% end %>

app/views/shared/_application_footer.html.erb
<div class="mastfoot app-footer">
  <div class="inner">
      <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <!-- Start of inner -->
  <div class="inner">
    <h3 class="masthead-brand">Kelvin Checo</h3>
    <!-- Start of nav-masthead -->
    <nav class="nav nav-masthead">
      <%= nav_generator "nav-link" %>
      <%= login_helper "nav-link" %>
    </nav>
    <!--/ End of nav-masthead -->
  </div>
  <!--/ End of inner -->
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
	<!-- Start of container -->
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <%= link_to "Write a New Blog", new_blog_path if logged_in?(:site_admin) %>
  </div>
  <!--/ End of container -->
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary mb-5 blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Start of container -->
  <div class="container">
  	<%= link_to "Kelvin Checo", root_path, class: "navbar-brand" %>

	  <!-- Start of navbar-collapse -->
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	      <%= nav_generator "nav-link" %>
	      <%= login_helper "nav-link" %>
	    </ul>
	  </div>
	  <!--/ End of navbar-collapse -->
	</div>
	<!--/ End of container -->
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-4 blog-sidebar">
  <!-- Start of sidebar-module -->
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <!--/ End of sidebar-module -->

  <!-- Start of sidebar-module -->
  <div class="sidebar-module">
    <%= source_helper("alert alert-info") %>
  </div>
  <!--/ End of sidebar-module -->

  <!-- Start of sidebar-module -->
  <div class="sidebar-module">
    <h4>Topics</h4>

    <% if @side_bar_topics %>

      <ul class="list-group">
      <% @side_bar_topics.each do |topic| %>
        <a class="list-group-item list-group-item-action justify-content-between" href="<%= topic_path(topic) %>">
          <%= topic.title %>
          <% if logged_in?(:site_admin) %>
            <span class="badge badge-primary badge-pill"><%= topic.blogs.count %></span>
          <% else %>
            <span class="badge badge-primary badge-pill"><%= topic.blogs.published.count %></span>
          <% end %>
        </a>
      <% end %>
      </ul>

    <% end %>
  </div>
  <!--/ End of sidebar-module -->

  <!-- Start of sidebar-module -->
  <div class="sidebar-module">
    <h4>Social Media</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
    </ol>
  </div>
  <!--/ End of sidebar-module -->
</div>

app/views/shared/_nav.html.erb
<nav class="<%= location %>">
  <div><%= link_to "Home", root_path%></div>
  <div><%= link_to "About Me", about_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
  <div><%= link_to "Contact Me", contact_path %></div>
</nav>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> | 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
	<!-- Start of container -->
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to "Learn more about me", about_path, class: "btn btn-primary" %>
      <%= link_to "See My Blog", blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
  <!--/ End of container -->
</section>

app/views/shared/_portfolio_nav.html.erb
<!-- Start of navbarHeader -->
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_generator "text-white", '<li>', '</li>' %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--/ End of navbarHeader -->
<!-- Start of navbar -->
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="<%= root_path %>" class="navbar-brand">Kelvin Checo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>
<!--/ End of navbar -->